### ISSUE TITLE
Code Missing

### ISSUE THREAD

**Issue by twhay** [elisabethbercy/Electronic_store#1]
Hi Elisabeth,

It appears that the code is missing from your project. Let me know if you need any help submitting the code to the GitHub repository, so that we can grade your project. Feel free to reach out on slack if you have any issues, or by replying to this ticket.

Best,
Tom

**Comment by elisabethbercy** [comment]
Helo Tom,
Thanks for reaching out, you said the repository is empty?

Sent from my mobile phone,
Please embrace the typos.
Stephanie Anne-Elisabeth BERCY
+(509) 476 164 41/ 415 008 35
-https://www.linkedin.com/in/stephaniebercy

**Comment by twhay** [comment]
I see that you have added your code. I'll go ahead and close this issue
